import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { TimesheetAnalysisResult } from "../types";

export function exportToPDF(result: TimesheetAnalysisResult, officialStartTime: string, officialEndTime: string) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  // Use built-in helvetica font (works without Arabic font files)
  doc.setFont("helvetica", "normal");

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  // Title (English fallback since Arabic requires custom font)
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Timesheet Analysis Report", pageWidth / 2, 20, { align: "center" });

  // Employee info
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Employee: ${result.employee_info.name}  |  ID: ${result.employee_info.id}  |  Role: ${result.employee_info.role}`, pageWidth / 2, 30, { align: "center" });
  doc.text(`Work Hours: ${officialStartTime} - ${officialEndTime}  |  Generated: ${new Date().toLocaleDateString("en")}`, pageWidth / 2, 36, { align: "center" });

  // KPIs summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Key Performance Indicators", margin, 48);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const kpis = [
    `Compliance: ${result.kpis.correctAttendancePercentage ?? 100}%`,
    `Delays: ${result.kpis.totalDelayMinutes} min`,
    `Early Exits: ${result.kpis.totalEarlyOutMinutes ?? 0} min`,
    `Absences: ${result.kpis.totalAbsences} days`,
    `Leaves: ${result.kpis.totalLeavesUsed} days`,
    `Work Hours: ${result.kpis.totalWorkHours ?? 0} hrs`,
    `Duplicate FP: ${result.kpis.totalDuplicateFingerprintDays ?? 0} days`,
  ];
  doc.text(kpis.join("   |   "), margin, 55);

  // Daily report table
  const tableHeaders = [["Day & Date", "Check In", "Check Out", "Hours", "Status", "Notes"]];

  const tableData = result.daily_report
    .filter((row) => !row.isWeekend)
    .map((row) => [
      `${row.dayName} (${row.date})`,
      row.checkIn || "-",
      row.checkOut || "-",
      row.workHours ? `${row.workHours}h` : "-",
      row.status,
      row.note || "-",
    ]);

  autoTable(doc, {
    startY: 62,
    head: tableHeaders,
    body: tableData,
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 35 },
      5: { cellWidth: "auto" },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 4) {
        const val = String(data.cell.raw);
        if (val.includes("تأخير") || val.includes("غياب") || val.includes("Delinquent") || val.includes("Absent")) {
          data.cell.styles.textColor = [220, 38, 38];
        } else if (val.includes("منتظم") || val.includes("Regular")) {
          data.cell.styles.textColor = [5, 150, 105];
        } else if (val.includes("إجازة") || val.includes("Leave")) {
          data.cell.styles.textColor = [217, 119, 6];
        }
      }
    },
  });

  // Late days summary
  const finalY = (doc as any).lastAutoTable?.finalY || 62;
  if (result.lateDaysSummary && result.lateDaysSummary.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Late Days Summary", margin, finalY + 12);

    const lateData = result.lateDaysSummary.map((item) => [
      `${item.dayName} (${item.date})`,
      item.time,
      `${item.delayMinutes} min`,
    ]);

    autoTable(doc, {
      startY: finalY + 16,
      head: [["Day & Date", "Check In Time", "Delay"]],
      body: lateData,
      styles: { font: "helvetica", fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: "bold" },
      margin: { left: margin },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Smart Timesheet Analyzer | ${result.employee_info.name} | Page ${i}/${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" }
    );
  }

  doc.save(`Timesheet_${result.employee_info.id || "employee"}.pdf`);
}
